#ifndef __CONSTRUCTOR_PRIORITY_H__
#define __CONSTRUCTOR_PRIORITY_H__

#define PRIORITY_PRINT_LIBRARY_VERSION 101
#define PRIORITY_LIBALLOC_REGISTER_MODULES 101
#define PRIORITY_LIBDBG_REGISTER_MODULES 101
#define PRIORITY_SYNC_LOCK_REGISTER_MODULES 102
#define PRIORITY_REGISTER_MAP_MODULES 103
#define PRIORITY_DEBUGGER 110
#define PRIORITY_DEFAULT_ALLOCATOR 111
#define PRIORITY_CONCURRENT 112
#define PRIORITY_OBJ_DEAMON 113
#define PRIORITY_REGISTER_CLASS 114

#endif
