/*
 * =====================================================================================
 *
 *       Filename:  debug_businesses.h
 *
 *    Description:  
 *
 *        Version:  1.0
 *        Created:  06/25/2015 06:02:18 PM
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  alan lin (), a1an1in@sina.com
 *   Organization:  
 *
 * =====================================================================================
 */

#ifndef __DEBUG_BUSINESSES_H__
#define __DEBUG_BUSINESSES_H__
enum debug_business_enum{
	DBG_BUSINESS_NORMAL = 0,
	DBG_BUSINESS_ALLOC,
	DBG_BUSINESS_CONTAINER,
	DBG_BUSINESS_LINKLIST,
	DBG_BUSINESS_HASHMAP,
	DBG_BUSINESS_CONCURRENT,
	MAX_DEBUG_BUSINESS_NUM
};
#define DBG_ALLOC_DBG_PANIC	 DBG_BUSINESS_ALLOC << 8 | DBG_DBG_PANIC 
#define DBG_ALLOC_FATAL		 DBG_BUSINESS_ALLOC << 8 | DBG_FATAL 
#define DBG_ALLOC_ERROR		 DBG_BUSINESS_ALLOC << 8 | DBG_ERROR 
#define DBG_ALLOC_WARNNING	 DBG_BUSINESS_ALLOC << 8 | DBG_WARNNING 
#define DBG_ALLOC_SUC		 DBG_BUSINESS_ALLOC << 8 | DBG_SUC 
#define DBG_ALLOC_CORRECT	 DBG_BUSINESS_ALLOC << 8 | DBG_CORRECT 
#define DBG_ALLOC_VIP 		 DBG_BUSINESS_ALLOC << 8 | DBG_VIP 
#define DBG_ALLOC_FLOW		 DBG_BUSINESS_ALLOC << 8 | DBG_FLOW 
#define DBG_ALLOC_IMPORTANT	 DBG_BUSINESS_ALLOC << 8 | DBG_IMPORTANT 
#define DBG_ALLOC_DETAIL	 DBG_BUSINESS_ALLOC << 8 | DBG_DETAIL 


#define LLIST_PANIC		 	 DBG_BUSINESS_LINKLIST << 8 | DBG_DBG_PANIC 
#define LLIST_FATAL			 DBG_BUSINESS_LINKLIST << 8 | DBG_FATAL 
#define LLIST_ERROR			 DBG_BUSINESS_LINKLIST << 8 | DBG_ERROR 
#define LLIST_WARNNING		 DBG_BUSINESS_LINKLIST << 8 | DBG_WARNNING 
#define LLIST_SUC			 DBG_BUSINESS_LINKLIST << 8 | DBG_SUC 
#define LLIST_CORRECT		 DBG_BUSINESS_LINKLIST << 8 | DBG_CORRECT 
#define LLIST_VIP 		  	 DBG_BUSINESS_LINKLIST << 8 | DBG_VIP 
#define LLIST_FLOW			 DBG_BUSINESS_LINKLIST << 8 | DBG_FLOW 
#define LLIST_IMPORTANT		 DBG_BUSINESS_LINKLIST << 8 | DBG_IMPORTANT 
#define LLIST_DETAIL		 DBG_BUSINESS_LINKLIST << 8 | DBG_DETAIL 

#define HMAP_PANIC		 	 DBG_BUSINESS_HASHMAP << 8 | DBG_DBG_PANIC 
#define HMAP_FATAL			 DBG_BUSINESS_HASHMAP << 8 | DBG_FATAL 
#define HMAP_ERROR			 DBG_BUSINESS_HASHMAP << 8 | DBG_ERROR 
#define HMAP_WARNNING		 DBG_BUSINESS_HASHMAP << 8 | DBG_WARNNING 
#define HMAP_SUC			 DBG_BUSINESS_HASHMAP << 8 | DBG_SUC 
#define HMAP_CORRECT		 DBG_BUSINESS_HASHMAP << 8 | DBG_CORRECT 
#define HMAP_VIP 		  	 DBG_BUSINESS_HASHMAP << 8 | DBG_VIP 
#define HMAP_FLOW			 DBG_BUSINESS_HASHMAP << 8 | DBG_FLOW 
#define HMAP_IMPORTANT		 DBG_BUSINESS_HASHMAP << 8 | DBG_IMPORTANT 
#define HMAP_DETAIL		 	 DBG_BUSINESS_HASHMAP << 8 | DBG_DETAIL 

#define CONCURRENT_PANIC		 DBG_BUSINESS_CONCURRENT << 8 | DBG_DBG_PANIC 
#define CONCURRENT_FATAL		 DBG_BUSINESS_CONCURRENT << 8 | DBG_FATAL 
#define CONCURRENT_ERROR		 DBG_BUSINESS_CONCURRENT << 8 | DBG_ERROR 
#define CONCURRENT_WARNNING		 DBG_BUSINESS_CONCURRENT << 8 | DBG_WARNNING 
#define CONCURRENT_SUC			 DBG_BUSINESS_CONCURRENT << 8 | DBG_SUC 
#define CONCURRENT_CORRECT		 DBG_BUSINESS_CONCURRENT << 8 | DBG_CORRECT 
#define CONCURRENT_VIP 		  	 DBG_BUSINESS_CONCURRENT << 8 | DBG_VIP 
#define CONCURRENT_FLOW			 DBG_BUSINESS_CONCURRENT << 8 | DBG_FLOW 
#define CONCURRENT_IMPORTANT	 DBG_BUSINESS_CONCURRENT << 8 | DBG_IMPORTANT 
#define CONCURRENT_DETAIL		 DBG_BUSINESS_CONCURRENT << 8 | DBG_DETAIL 
#endif
